import modal
import os
from fastapi import FastAPI, UploadFile, File, HTTPException

stub = modal.Stub(image=modal.Image.debian_slim().pip_install("openai~=0.27.0"))


@stub.webhook(method="POST", secret=modal.Secret.from_name("my-openai-secret"))
def semantic_detection(labels: list):
    import openai

    def get_species(labels):
        species = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": f"""If the term does not describe a dog or dog breed, eliminate it. From the remaining list, 
  if there is a specific dog breed in the list, tell me the dog breed. If there are more than two items remaining in the list, 
  pick the most specific dog breed and return that. Keep your answer between 1 and 3 words. Here is the list: {labels}"""}
            ]
        )
        return species["choices"][0]["message"]["content"]
        
    def predict_size(species):
        gpt_size = 0
        fur_output = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant and an expert on dogs."},
                {"role": "user", "content": f"How fluffy is the fur of {species} compared to the average dog? One word response: less or more"}
            ]
        )
        size_output = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant and an expert on dogs."},
                {"role": "user", "content": f"What is the size of an average {species} compared to the average dog? One word response: big or small"}
            ]
        )
        fur_output = fur_output["choices"][0]["message"]["content"].lower()
        size_output = size_output["choices"][0]["message"]["content"].lower()
        try:
            if (size_output.__contains__('big') and fur_output.__contains__('less')):
                gpt_size = 1
            elif (size_output.__contains__('big') and fur_output.__contains__('more')):
                gpt_size = 2
            elif (size_output.__contains__('small') and fur_output.__contains__('less')):
                gpt_size = 3
            elif (size_output.__contains__('small') and fur_output.__contains__('more')):
                gpt_size = 4
            else:
                raise HTTPException(status_code=100, detail="GPT-3 failed to predict size")
        
        except HTTPException as e:
            print(e)
            raise e
        return gpt_size
    
    def predict_weight(species):
        gpt_weight = 0
        voice_output = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant and an expert on dogs."},
                {"role": "user", "content": f"What is the average weight of {species}. ? One whole number as a response ONLY, no words"}
            ]
        )
        voice_output = voice_output["choices"][0]["message"]["content"].lower()
        try:
            if (weight_int <= 10):
                gpt_weight = 4
            elif (weight_int > 10 and weight_int <= 40):
                gpt_weight = 3
            elif (weight_int > 40 and weight_int <= 100):
                gpt_weight = 2
            elif (weight_int > 100):
                gpt_weight = 1
            else:
                raise HTTPException(status_code=100, detail="GPT-3 failed to predict weight")
        except HTTPException as e:
            print(e)
            raise e
        return gpt_weight
    
    def predict_full(species):
        voice_output = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant and an expert on dogs."},
                {"role": "user", "content": f"""Establish an average Labrador Retriever having a voice pitch of 2, an average German Shepherd having a voice pitch of 1, 
  an average Toy Dog having a voice pitch of 3, an average Poodle having a voice pitch of 3, an average Chihuahua having a voice pitch of 4, 
  and an average Husky having a voice pitch of 2. Output the result as 1, 2, 3, or 4, with 1 being lowest pitched and 4 being highest pitched.
  What pitch of voice would an {species} average have? Give just one number as the answer."""}
            ]
        )
    
    #picks out species labels from those generated by object detection
    species = get_species(labels)
    #prediction based on size and weight priors
    voice_pred1 = (predict_size(species) + predict_weight(species) + 1) // 2
    #prediction based purely on chatgpt output
    voice_pred2 = predict_full(species)
    #we are going to average the two predictions to get a more accurate result
    voice_pred = (voice_pred1 + voice_pred2) // 2
    return voice_pred

